### ISSUE TITLE
SassyStudio throws exception while saving .scss

### ISSUE THREAD

**Issue by wladyslawczyzewski** [darrenkopp/SassyStudio#73]
HI,

Yesterday I installed the newest version of SassyStudio (0.8.9.0) and noticed that SassyStudio throws FileNotFoundException while I tried to compile the css.

Could you please inspect this behavior?

There is a full stack trace of exception from Output window in VS2012 (Upd4)

```
12:11:58.807 PM: Failed to compile css.
[FileNotFoundException]Could not load file or assembly 'LibSass.x86.dll' or one of its dependencies. The specified module could not be found.
  at LibSassNet.SassCompiler..ctor()
  at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<.ctor>b__0()
  at System.Lazy`1.CreateValue()
  at System.Lazy`1.LazyInitValue()
  at System.Lazy`1.get_Value()
  at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.Compile(FileInfo source, FileInfo output)
  at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<>c__DisplayClass3.<CompileAsync>b__2()
  at System.Threading.Tasks.Task.InnerInvoke()
  at System.Threading.Tasks.Task.Execute()
```

   --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at SassyStudio.Editor.GenerateCssOnSave.<GenerateCss>d__14.MoveNext()

**Comment by don01001100** [comment]
@darrenkopp, I installed that using Visual Studio Ultimate 2012 version 11.0.61030.00 Update 4 and still got the error. My stack trace is identical:

    11:33:18.318 AM: Failed to compile css.
    [FileNotFoundException]Could not load file or assembly 'LibSass.x86.dll' or one of its dependencies. The specified module could not be found.
       at LibSassNet.SassCompiler..ctor()
       at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<.ctor>b__0()
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.Compile(FileInfo source, FileInfo output)
       at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<>c__DisplayClass3.<CompileAsync>b__2()
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SassyStudio.Editor.GenerateCssOnSave.<GenerateCss>d__14.MoveNext()
