### ISSUE TITLE
Unable to use @import after latest update

### ISSUE THREAD

**Issue by jefftheswede** [darrenkopp/SassyStudio#76]
Hi Darren,

I've been having problems compiling SASS with an import after the latest update (it was working fine before). If I drop the contents of the imported file in my file instead of the import line, everything works fine. Here's what I get for an error:

===============================================
02:35:31.281 PM: Failed to compile css.
[SassCompileException]Unknown error occurred

   at LibSassNet.SassCompiler.CompileFile(String inputPath, OutputStyle outputStyle, String sourceMapPath, Boolean includeSourceComments, Int32 precision, IEnumerable`1 additionalIncludePaths)
   at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.Compile(FileInfo source, FileInfo output)
   at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<>c__DisplayClass3.<CompileAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SassyStudio.Editor.GenerateCssOnSave.<GenerateCss>d__14.MoveNext()

02:35:31.281 PM: Compile complete.
===============================================

Thanks!
Jeff

**Comment by alan-zetland** [comment]
I've just installed this for the first time and have the same issue, non-import processing is fine, but anything that attempts an import is failing with the above message.

**Comment by darrenkopp** [comment]
Odd, I'm not having that issue on VS2013. 
![image](https://cloud.githubusercontent.com/assets/135476/6828826/590a29e4-d2d5-11e4-89f2-2a2add6198bd.png)


I'd say for the interim until i investigate, just install the previous version. https://github.com/darrenkopp/SassyStudio/releases/tag/0.8.9.1

**Comment by darrenkopp** [comment]
link for vs2013: https://github.com/darrenkopp/SassyStudio2013/releases/tag/0.1.7.0

**Comment by alan-zetland** [comment]
Thanks Darren, I installed the 0.8.9.1 version and that seems to have resolved the problem. Thanks for the quick response.

**Comment by jefftheswede** [comment]
Thanks a lot Darren! The 2013 0.1.7.0 release works well. Much appreciated.

**Comment by alan-zetland** [comment]
I also just installed the 2013 v0.1.7.0 and can confirm this works OK too.  Thanks very much.

**Comment by paullferguson** [comment]
Was a strange issue but stepping back to 0.8.9.1 helped me, I'm on VS 2012 11.0610
