### ISSUE TITLE
Support for unix style paths

### ISSUE THREAD

**Issue by sjk07** [darrenkopp/SassyStudio#77]
I was trying to run SassyStudio in VS 2013 on OSX via Parallels.
but i kept getting a file not found / unreadable exception. Im thinking the issue is the path for the file is coming up as a network drive path, and maybe this unix style path that doesn't play well with sassy.

this is what the path looks like:
`\\psf\Home\dev\website\Content\sass\Tool.scss`

Here is the full stack trace:
```bash
Failed to compile css.
[SassCompileException]Error: File to read not found or unreadable: \\psf\Home\dev\website\Content\sass\Tool.scss

   at LibSassNet.SassCompiler.CompileFile(String inputPath, OutputStyle outputStyle, String sourceMapPath, Boolean includeSourceComments, Int32 precision, IEnumerable`1 additionalIncludePaths)
   at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.Compile(FileInfo source, FileInfo output)
   at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<>c__DisplayClass3.<CompileAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was
 thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SassyStudio.Editor.CompileScssOnSave.<GenerateCss>d__1d.MoveNext()
```

**Comment by darrenkopp** [comment]
yeah, that's a limitation in libsass unfortunately, and has been there for a while. i've also been bitten by this.

i can revisit and see if it's something i'm doing, but it didn't work even when i was using nsass.
