### ISSUE TITLE
Sassystudio and compass compile error

### ISSUE THREAD

**Issue by danielnyborg** [darrenkopp/SassyStudio#78]
Hi,

I'm trying to use Sassystudio and compass for SASS references like @import "compass/CSS3"

However on compile I keep getting the following error:

08:12:01.288 : Failed to compile css.
[SassCompileException]C:/Ruby22/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/stylesheets/compass/_support.scss:152: named arguments must precede variable-length argument

   at LibSassNet.SassCompiler.CompileFile(String inputPath, OutputStyle outputStyle, String sourceMapPath, Boolean includeSourceComments, Int32 precision, IEnumerable`1 additionalIncludePaths)
   at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.Compile(FileInfo source, FileInfo output)
   at SassyStudio.Integration.LibSass.LibSassNetDocumentCompiler.<>c__DisplayClass3.<CompileAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SassyStudio.Editor.GenerateCssOnSave.<GenerateCss>d__14.MoveNext()

Any idea of what is causing this? Thanks!

**Comment by darrenkopp** [comment]
It looks like you are using the default compiler, which I don't think support compass the last time I checked (compass uses many non-sass functions that are defined in ruby). Have you tried putting your ruby path into the options of SassyStudio (which causes it SassyStudio to then use the compass compiler)?

`Tools > options > sassy studio > ruby path` should be set to `c:\Ruby22`.

**Comment by danielnyborg** [comment]
Yeah, i've tried using the following:

"c:\Ruby22", causing:
Error: File to import not found or unreadable: compass/CSS3.

"c:\Ruby22\bin", causing:
10:17:07.704 : Failed to compile css.
[SassCompileException]C:/Ruby22/lib/ruby/gems/2.2.0/gems/compass-core-1.0.0/stylesheets/compass/_support.scss:152: named arguments must precede variable-length argument

Here's my current configurations:

![sassy-config](https://cloud.githubusercontent.com/assets/10737802/7239597/8ca4c094-e7ab-11e4-873d-e96636408a6f.png)

Appreciate any insights you may have on the issue - thanks.
